name: oxcode_payroll
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.1

dependencies:
  firebase_auth: ^6.1.3
  firebase_core: ^4.3.0
  cloud_firestore:
  cloud_functions:
  firebase_storage: 13.0.5
  http: ^1.1.0
  flutter:
    sdk: flutter
  flutter_screenutil: 5.9.3
  google_fonts: ^7.0.2
  intl: ^0.20.2
  lucide_icons_flutter: ^3.1.9
  provider: ^6.1.5+1
  table_calendar: ^3.1.2
  flutter_svg: ^2.0.10+1
  image_picker: ^1.2.1
  path_provider: ^2.1.5
  path: ^1.9.1
  camera: ^0.11.3
  flutter_local_notifications: ^20.0.0
  timezone: ^0.10.1
  local_auth: ^3.0.0
  network_info_plus: ^7.0.0
  geolocator: ^14.0.2
  mobile_scanner: ^7.2.0
  pdf: ^3.11.3
  printing: ^5.14.2
  shared_preferences: ^2.2.3
  device_info_plus: ^11.0.1
  connectivity_plus: ^6.0.2
  go_router: ^14.1.4
  dio: ^5.4.3+1
  data_table_2: ^2.5.11
  fl_chart: ^0.68.0
  file_picker: ^8.0.5
  csv: ^5.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/png/
    - assets/svg/
