name: oxcode_payroll
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.1

dependencies:
  firebase_auth: ^6.1.3
  firebase_core: ^4.3.0
  cloud_firestore: 
  flutter:
    sdk: flutter
  flutter_screenutil: 5.9.3
  google_fonts: ^7.0.2
  intl: ^0.20.2
  lucide_icons_flutter: ^3.1.9
  provider: ^6.1.5+1
  table_calendar: ^3.1.2
  flutter_svg: ^2.0.10+1
  image_picker: ^1.2.1
  path_provider: ^2.1.5
  path: ^1.9.1
  camera: ^0.11.3
  flutter_local_notifications: ^20.0.0
  timezone: ^0.10.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/png/
    - assets/svg/
